import json
import os
import secrets
import sqlite3
from functools import wraps
from urllib.parse import parse_qs, urlencode, urlparse
from urllib.request import Request, urlopen

from flask import Flask, flash, g, redirect, render_template, request, send_from_directory, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:
    psycopg = None
    dict_row = None

app = Flask(__name__)
app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", "change-this-secret-key")
app.config["DATABASE"] = os.environ.get("DATABASE_PATH", os.path.join(app.root_path, "root.sqlite3"))
app.config["DATABASE_URL"] = os.environ.get("DATABASE_URL")
app.config["USE_POSTGRES"] = bool(app.config["DATABASE_URL"])
app.config["SEND_FILE_MAX_AGE_DEFAULT"] = 0


def load_google_credentials():
    client_id = os.environ.get("GOOGLE_CLIENT_ID")
    client_secret = os.environ.get("GOOGLE_CLIENT_SECRET")
    if client_id and client_secret:
        return client_id, client_secret

    credentials_path = os.environ.get("GOOGLE_CLIENT_SECRET_FILE")
    if not credentials_path:
        credentials_path = next(
            (os.path.join(app.root_path, name) for name in os.listdir(app.root_path) if name.startswith("client_secret") and name.endswith(".json")),
            None,
        )
    if not credentials_path or not os.path.exists(credentials_path):
        return client_id, client_secret

    try:
        with open(credentials_path, encoding="utf-8") as credentials_file:
            credentials = json.load(credentials_file).get("web", {})
    except (OSError, json.JSONDecodeError):
        return client_id, client_secret
    return client_id or credentials.get("client_id"), client_secret or credentials.get("client_secret")


app.config["GOOGLE_CLIENT_ID"], app.config["GOOGLE_CLIENT_SECRET"] = load_google_credentials()


@app.route("/series/<path:filename>")
def series_file(filename):
    return send_from_directory(os.path.join(app.root_path, "Series"), filename)


class PostgresConnection:
    def __init__(self, connection):
        self.connection = connection

    def execute(self, query, params=()):
        return self.connection.execute(query.replace("?", "%s"), params)

    def commit(self):
        self.connection.commit()

    def close(self):
        self.connection.close()


def get_db():
    if "db" not in g:
        if app.config["USE_POSTGRES"]:
            if psycopg is None:
                raise RuntimeError("DATABASE_URL cần cài psycopg[binary].")
            g.db = PostgresConnection(psycopg.connect(app.config["DATABASE_URL"], row_factory=dict_row))
        else:
            g.db = sqlite3.connect(app.config["DATABASE"])
            g.db.row_factory = sqlite3.Row
    return g.db


def execute_insert_user(sql, params):
    if app.config["USE_POSTGRES"]:
        return get_db().execute(sql + " RETURNING id", params).fetchone()["id"]
    return get_db().execute(sql, params).lastrowid


@app.teardown_appcontext
def close_db(error=None):
    db = g.pop("db", None)
    if db is not None:
        db.close()


def init_db():
    db = get_db()
    if app.config["USE_POSTGRES"]:
        db.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT,
                google_id TEXT UNIQUE,
                role TEXT NOT NULL DEFAULT 'reader',
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE TABLE IF NOT EXISTS articles (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                slug TEXT NOT NULL UNIQUE,
                category TEXT NOT NULL,
                title TEXT NOT NULL,
                excerpt TEXT NOT NULL,
                time TEXT NOT NULL DEFAULT '5 phút',
                tone TEXT NOT NULL DEFAULT 'moss',
                author TEXT NOT NULL,
                body TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'published',
                user_id INTEGER REFERENCES users(id),
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                reviewed_at TIMESTAMPTZ,
                cover_image TEXT
            );
            CREATE TABLE IF NOT EXISTS episodes (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                kind TEXT NOT NULL CHECK (kind IN ('Radio', 'Podcast')),
                title TEXT NOT NULL,
                description TEXT NOT NULL,
                duration TEXT NOT NULL,
                tone TEXT NOT NULL DEFAULT 'moss',
                audio_url TEXT,
                youtube_url TEXT,
                status TEXT NOT NULL DEFAULT 'published',
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                cover_image TEXT,
                UNIQUE (kind, title)
            );
        """)
    else:
        db.executescript("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT,
            google_id TEXT UNIQUE,
            role TEXT NOT NULL DEFAULT 'reader',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS articles (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            slug TEXT NOT NULL UNIQUE,
            category TEXT NOT NULL,
            title TEXT NOT NULL,
            excerpt TEXT NOT NULL,
            time TEXT NOT NULL DEFAULT '5 phút',
            tone TEXT NOT NULL DEFAULT 'moss',
            author TEXT NOT NULL,
            body TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'published',
            user_id INTEGER,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            reviewed_at TEXT,
            cover_image TEXT,
            FOREIGN KEY (user_id) REFERENCES users(id)
        );
        CREATE TABLE IF NOT EXISTS episodes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            kind TEXT NOT NULL CHECK (kind IN ('Radio', 'Podcast')),
            title TEXT NOT NULL,
            description TEXT NOT NULL,
            duration TEXT NOT NULL,
            tone TEXT NOT NULL DEFAULT 'moss',
            audio_url TEXT,
            youtube_url TEXT,
            status TEXT NOT NULL DEFAULT 'published',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            cover_image TEXT,
            UNIQUE (kind, title)
        );
        """)
    migrate_schema(db)
    if db.execute("SELECT COUNT(*) AS total FROM articles").fetchone()["total"] == 0:
        seed_content(db)
    if db.execute("SELECT COUNT(*) AS total FROM episodes").fetchone()["total"] == 0:
        seed_episodes(db)
    if db.execute("SELECT COUNT(*) AS total FROM users WHERE role = 'admin'").fetchone()["total"] == 0:
        admin_email = os.environ.get("ADMIN_EMAIL", "admin@root.local")
        admin_password = os.environ.get("ADMIN_PASSWORD", "admin12345")
        if app.config["USE_POSTGRES"]:
            db.execute("INSERT INTO users (name, email, password_hash, role) VALUES (%s, %s, %s, 'admin') ON CONFLICT (email) DO NOTHING", ("Root Admin", admin_email, generate_password_hash(admin_password)))
        else:
            db.execute("INSERT OR IGNORE INTO users (name, email, password_hash, role) VALUES (?, ?, ?, 'admin')", ("Root Admin", admin_email, generate_password_hash(admin_password)))
    db.commit()


def migrate_schema(db):
    if app.config["USE_POSTGRES"]:
        return
    tables = {
        "users": {
            "password_hash": "TEXT",
            "google_id": "TEXT",
            "role": "TEXT NOT NULL DEFAULT 'reader'",
            "created_at": "TEXT",
        },
        "articles": {
            "time": "TEXT NOT NULL DEFAULT '5 phút'",
            "tone": "TEXT NOT NULL DEFAULT 'moss'",
            "status": "TEXT NOT NULL DEFAULT 'published'",
            "user_id": "INTEGER",
            "created_at": "TEXT",
            "reviewed_at": "TEXT",
            "cover_image": "TEXT",
        },
        "episodes": {
            "audio_url": "TEXT",
            "youtube_url": "TEXT",
            "status": "TEXT NOT NULL DEFAULT 'published'",
            "created_at": "TEXT",
            "cover_image": "TEXT",
        },
    }
    for table, columns in tables.items():
        existing = {row[1] for row in db.execute(f"PRAGMA table_info({table})")}
        for column, definition in columns.items():
            if column not in existing:
                db.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")
        if "created_at" in columns:
            db.execute(f"UPDATE {table} SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")


def seed_content(db):
    with open(os.path.join(app.root_path, "content.json"), encoding="utf-8") as content_file:
        content = json.load(content_file)
    for article in content["articles"]:
        db.execute("INSERT INTO articles (slug, category, title, excerpt, time, tone, author, body, cover_image) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", (article["id"], article["category"], article["title"], article["excerpt"], article.get("time", "5 phút"), article.get("tone", "moss"), article["author"], json.dumps(article.get("sections", []), ensure_ascii=False), article.get("cover_image")))


def seed_episodes(db):
    with open(os.path.join(app.root_path, "content.json"), encoding="utf-8") as content_file:
        content = json.load(content_file)
    for episode in content.get("episodes", []):
        values = (episode["kind"], episode["title"], episode["description"], episode.get("time", ""), episode.get("tone", "moss"), episode.get("audio_url"), episode.get("youtube_url"), episode.get("cover_image"))
        if app.config["USE_POSTGRES"]:
            db.execute("INSERT INTO episodes (kind, title, description, duration, tone, audio_url, youtube_url, cover_image) VALUES (%s, %s, %s, %s, %s, %s, %s, %s) ON CONFLICT (kind, title) DO NOTHING", values)
        else:
            db.execute("INSERT OR IGNORE INTO episodes (kind, title, description, duration, tone, audio_url, youtube_url, cover_image) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", values)


def load_episodes(kind=None):
    query = "SELECT *, duration AS time FROM episodes WHERE status = 'published'"
    params = ()
    if kind is not None:
        query += " AND kind = ?"
        params = (kind,)
    query += " ORDER BY created_at ASC, id ASC"
    return get_db().execute(query, params).fetchall()


def youtube_embed_url(value):
    """Return a safe YouTube embed URL for common share-link formats."""
    if not value:
        return None
    parsed = urlparse(value.strip())
    host = parsed.netloc.lower().split(":", 1)[0]
    video_id = None
    if host in {"youtu.be", "www.youtu.be"}:
        video_id = parsed.path.strip("/").split("/")[0]
    elif host in {"youtube.com", "www.youtube.com", "m.youtube.com"}:
        if parsed.path == "/watch":
            video_id = parse_qs(parsed.query).get("v", [None])[0]
        elif parsed.path.startswith(("/embed/", "/shorts/")):
            video_id = parsed.path.split("/")[2]
    if video_id and len(video_id) == 11:
        return f"https://www.youtube.com/embed/{video_id}"
    return None


@app.before_request
def load_current_user():
    user_id = session.get("user_id")
    g.user = get_db().execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone() if user_id else None


@app.context_processor
def inject_user():
    return {"current_user": g.get("user")}


def article_view(row):
    article = dict(row)
    article["sections"] = json.loads(article.pop("body"))
    return article


def login_required(view):
    @wraps(view)
    def wrapped(*args, **kwargs):
        if g.user is None:
            flash("Bạn cần đăng nhập để tiếp tục.", "error")
            return redirect(url_for("sign", next=request.path))
        return view(*args, **kwargs)
    return wrapped


def admin_required(view):
    @wraps(view)
    @login_required
    def wrapped(*args, **kwargs):
        if g.user["role"] != "admin":
            flash("Khu vực này chỉ dành cho quản trị viên.", "error")
            return redirect(url_for("home"))
        return view(*args, **kwargs)
    return wrapped


@app.after_request
def disable_development_cache(response):
    response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, max-age=0"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "0"
    return response


@app.errorhandler(404)
def not_found(error):
    return render_template("404.html"), 404


@app.route("/chinh-sach-bao-mat")
def privacy():
    return render_template("legal.html", page_title="Chính sách bảo mật", active="landing")


@app.route("/dieu-khoan-dich-vu")
def terms():
    return render_template("legal.html", page_title="Điều khoản dịch vụ", active="landing")


def page_context(active="home", **values):
    categories = {"hoc-thuat": "Học thuật", "cam-xuc": "Cảm xúc", "chua-lanh": "Chữa lành"}
    return {"active": active, "categories": categories, **values}


@app.route("/")
def landingpage():
    return render_template("landingpage.html", **page_context("landing"))


@app.route("/home")
def home():
    rows = get_db().execute("SELECT * FROM articles WHERE status = 'published' ORDER BY created_at DESC").fetchall()
    return render_template("home.html", **page_context("home", articles=[article_view(row) for row in rows], episodes=load_episodes()))


@app.route("/tim-kiem")
def search():
    query = request.args.get("q", "").strip()
    rows = []
    if query:
        pattern = f"%{query}%"
        rows = get_db().execute("SELECT * FROM articles WHERE status = 'published' AND (title LIKE ? OR excerpt LIKE ? OR body LIKE ?) ORDER BY created_at DESC", (pattern, pattern, pattern)).fetchall()
    return render_template("search.html", **page_context("search", query=query, articles=[article_view(row) for row in rows]))


@app.route("/sign", methods=["GET", "POST"])
def sign():
    if request.method == "POST":
        user = get_db().execute("SELECT * FROM users WHERE email = ?", (request.form["email"].strip().lower(),)).fetchone()
        if user and user["password_hash"] and check_password_hash(user["password_hash"], request.form["password"]):
            session["user_id"] = user["id"]
            return redirect(request.args.get("next") or url_for("home"))
        flash("Email hoặc mật khẩu chưa đúng.", "error")
    return render_template("sign.html", **page_context("sign", google_enabled=bool(app.config["GOOGLE_CLIENT_ID"])))


@app.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        name, email, password = request.form["name"].strip(), request.form["email"].strip().lower(), request.form["password"]
        if len(password) < 8:
            flash("Mật khẩu cần tối thiểu 8 ký tự.", "error")
        else:
            try:
                user_id = execute_insert_user("INSERT INTO users (name, email, password_hash) VALUES (?, ?, ?)", (name, email, generate_password_hash(password)))
                get_db().commit()
                session["user_id"] = user_id
                return redirect(url_for("home"))
            except (sqlite3.IntegrityError, psycopg.IntegrityError if psycopg else sqlite3.IntegrityError):
                flash("Email này đã được đăng ký.", "error")
    return render_template("register.html", **page_context("register", google_enabled=bool(app.config["GOOGLE_CLIENT_ID"])))


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("home"))


@app.route("/auth/google")
def google_login():
    if not app.config["GOOGLE_CLIENT_ID"] or not app.config["GOOGLE_CLIENT_SECRET"]:
        flash("Google OAuth chưa được cấu hình trên máy chủ.", "error")
        return redirect(url_for("sign"))
    state = secrets.token_urlsafe(24)
    session["google_state"] = state
    session["google_next"] = request.args.get("next") or request.referrer or url_for("home")
    params = {"client_id": app.config["GOOGLE_CLIENT_ID"], "redirect_uri": url_for("google_callback", _external=True), "response_type": "code", "scope": "openid email profile", "state": state, "access_type": "offline"}
    return redirect("https://accounts.google.com/o/oauth2/v2/auth?" + urlencode(params))


@app.route("/auth/google/callback")
def google_callback():
    if request.args.get("state") != session.pop("google_state", None):
        flash("Phiên đăng nhập Google không hợp lệ.", "error")
        return redirect(url_for("sign"))
    data = urlencode({"code": request.args.get("code"), "client_id": app.config["GOOGLE_CLIENT_ID"], "client_secret": app.config["GOOGLE_CLIENT_SECRET"], "redirect_uri": url_for("google_callback", _external=True), "grant_type": "authorization_code"}).encode()
    with urlopen(Request("https://oauth2.googleapis.com/token", data=data, headers={"Content-Type": "application/x-www-form-urlencoded"})) as response:
        token = json.loads(response.read())
    with urlopen(Request("https://openidconnect.googleapis.com/v1/userinfo", headers={"Authorization": "Bearer " + token["access_token"]})) as response:
        profile = json.loads(response.read())
    db = get_db()
    user = db.execute("SELECT * FROM users WHERE google_id = ? OR email = ?", (profile["sub"], profile["email"].lower())).fetchone()
    if user is None:
        user_id = execute_insert_user("INSERT INTO users (name, email, google_id) VALUES (?, ?, ?)", (profile.get("name", "Root member"), profile["email"].lower(), profile["sub"]))
    else:
        user_id = user["id"]
        db.execute("UPDATE users SET google_id = ? WHERE id = ?", (profile["sub"], user_id))
    db.commit()
    session["user_id"] = user_id
    return redirect(session.pop("google_next", None) or url_for("home"))


@app.route("/kien-thuc")
def kien_thuc():
    rows = get_db().execute("SELECT * FROM articles WHERE status = 'published' ORDER BY created_at DESC").fetchall()
    return render_template("KienThuc.html", **page_context("kien-thuc", articles=[article_view(row) for row in rows]))


@app.route("/kien-thuc/<category>")
def category_page(category):
    context = page_context()
    if category not in context["categories"]:
        return render_template("404.html"), 404
    rows = get_db().execute("SELECT * FROM articles WHERE status = 'published' AND category = ? ORDER BY created_at DESC", (category,)).fetchall()
    return render_template("category.html", **page_context(category, category_key=category, category_name=context["categories"][category], articles=[article_view(row) for row in rows]))


@app.route("/bai-viet/<article_id>")
def article_detail(article_id):
    row = get_db().execute("SELECT * FROM articles WHERE slug = ? AND status = 'published'", (article_id,)).fetchone()
    if row is None:
        return render_template("404.html"), 404
    article = article_view(row)
    return render_template("article_detail.html", **page_context("kien-thuc", article=article, category_name=page_context()["categories"][article["category"]]))


@app.route("/radio")
def radio():
    return render_template("Radio.html", **page_context("radio", episodes=load_episodes("Radio")))


@app.route("/radio/<int:episode_id>")
def radio_detail(episode_id):
    episode = get_db().execute("SELECT *, duration AS time FROM episodes WHERE id = ? AND kind = 'Radio' AND status = 'published'", (episode_id,)).fetchone()
    if episode is None:
        return render_template("404.html"), 404
    episode = dict(episode)
    episode["youtube_embed_url"] = youtube_embed_url(episode.get("youtube_url"))
    return render_template("radio_detail.html", **page_context("radio", episode=episode, episodes=load_episodes("Radio")))


@app.route("/podcast")
def podcast():
    return render_template("Podcast.html", **page_context("podcast", episodes=load_episodes("Podcast")))


@app.route("/podcast/<int:episode_id>")
def podcast_detail(episode_id):
    episode = get_db().execute("SELECT *, duration AS time FROM episodes WHERE id = ? AND kind = 'Podcast' AND status = 'published'", (episode_id,)).fetchone()
    if episode is None:
        return render_template("404.html"), 404
    episode = dict(episode)
    episode["youtube_embed_url"] = youtube_embed_url(episode.get("youtube_url"))
    return render_template("podcast_detail.html", **page_context("podcast", episode=episode, episodes=load_episodes("Podcast")))


@app.route("/viet-bai", methods=["GET", "POST"])
@login_required
def write_article():
    if request.method == "POST":
        title = request.form["title"].strip()
        slug = "-".join(title.lower().split())[:80] + "-" + secrets.token_hex(3)
        sections = [("Nội dung", request.form["body"].strip())]
        get_db().execute("INSERT INTO articles (slug, category, title, excerpt, time, tone, author, body, status, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?)", (slug, request.form["category"], title, request.form["excerpt"].strip(), request.form.get("time", "5 phút"), "moss", g.user["name"], json.dumps(sections, ensure_ascii=False), g.user["id"]))
        get_db().commit()
        flash("Bài viết đã được gửi và đang chờ admin duyệt.", "success")
        return redirect(url_for("my_articles"))
    return render_template("write_article.html", **page_context("write"))


@app.route("/bai-viet-cua-toi")
@login_required
def my_articles():
    rows = get_db().execute("SELECT * FROM articles WHERE user_id = ? ORDER BY created_at DESC", (g.user["id"],)).fetchall()
    return render_template("my_articles.html", **page_context("write", articles=rows))


@app.route("/trang-ca-nhan")
@login_required
def profile():
    counts = get_db().execute("SELECT status, COUNT(*) AS total FROM articles WHERE user_id = ? GROUP BY status", (g.user["id"],)).fetchall()
    count_by_status = {row["status"]: row["total"] for row in counts}
    return render_template("profile.html", **page_context("profile", article_count=sum(count_by_status.values()), pending_count=count_by_status.get("pending", 0), published_count=count_by_status.get("published", 0), rejected_count=count_by_status.get("rejected", 0)))


@app.route("/admin")
@admin_required
def admin_dashboard():
    rows = get_db().execute("SELECT articles.*, users.email AS submitter_email FROM articles LEFT JOIN users ON users.id = articles.user_id ORDER BY CASE status WHEN 'pending' THEN 0 ELSE 1 END, created_at DESC").fetchall()
    return render_template("admin.html", **page_context("admin", articles=rows, episodes=load_episodes()))


@app.route("/admin/episodes/<int:episode_id>/youtube", methods=["POST"])
@admin_required
def update_episode_youtube(episode_id):
    youtube_url = request.form.get("youtube_url", "").strip()
    if youtube_url and youtube_embed_url(youtube_url) is None:
        flash("Link YouTube chưa đúng định dạng.", "error")
        return redirect(url_for("admin_dashboard"))
    get_db().execute("UPDATE episodes SET youtube_url = ? WHERE id = ?", (youtube_url or None, episode_id))
    get_db().commit()
    flash("Đã cập nhật video YouTube cho tập.", "success")
    return redirect(url_for("admin_dashboard"))


@app.route("/admin/articles/<int:article_id>/approve", methods=["POST"])
@admin_required
def approve_article(article_id):
    get_db().execute("UPDATE articles SET status = 'published', reviewed_at = CURRENT_TIMESTAMP WHERE id = ?", (article_id,))
    get_db().commit()
    return redirect(url_for("admin_dashboard"))


@app.route("/admin/articles/<int:article_id>/reject", methods=["POST"])
@admin_required
def reject_article(article_id):
    get_db().execute("UPDATE articles SET status = 'rejected', reviewed_at = CURRENT_TIMESTAMP WHERE id = ?", (article_id,))
    get_db().commit()
    return redirect(url_for("admin_dashboard"))


@app.route("/admin/viet-bai", methods=["GET", "POST"])
@admin_required
def admin_write_article():
    if request.method == "POST":
        title = request.form["title"].strip()
        slug = "-".join(title.lower().split())[:80] + "-" + secrets.token_hex(3)
        body = json.dumps([("Nội dung", request.form["body"].strip())], ensure_ascii=False)
        get_db().execute("INSERT INTO articles (slug, category, title, excerpt, time, tone, author, body, status, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'published', ?)", (slug, request.form["category"], title, request.form["excerpt"].strip(), request.form.get("time", "5 phút"), "moss", g.user["name"], body, g.user["id"]))
        get_db().commit()
        return redirect(url_for("admin_dashboard"))
    return render_template("write_article.html", **page_context("admin", admin_mode=True))


with app.app_context():
    init_db()


if __name__ == "__main__":
    app.run(debug=os.environ.get("FLASK_DEBUG", "0") == "1", host=os.environ.get("HOST", "127.0.0.1"), port=int(os.environ.get("PORT", "5000")))